import { Checks } from "../models/cars.model";

export const CHECKS_INIT: Checks = {
  unidad_luces: false,
  cuarto_luces: false,
  antena: false,
  espejos_laterales: false,
  cristales: false,
  emblemas: false,
  llantas: false,
  tapones_gasolina: false,
  carroceria_sin_golpes: false,
  claxon: false,
  instrumentos_tablero: false,
  aire_acondicionado: false,
  limpiadores: false,
  radio_estereo: false,
  encendedor: false,
  espejo_retrovisor: false,
  ceniceros: false,
  botones_interiores: false,
  manijas_interiores: false,
  tapetes: false,
  vestiduras: false,
  gato: false,
  maneral_gato: false,
  llave_ruedas: false,
  herramientas: false,
  traing_seguridad: false,
  llanta_refaccion: false,
  extinguidor: false,
  tapon_aceite: false,
  tapon_radiador: false,
  filtro_aceite: false,
  bateria: false,
  filtro_aire: false,
};

type CheckKey = keyof Checks;

export const CHECKS_FIELDS: Array<{ key: CheckKey; label: string }> = [
  { key: 'unidad_luces', label: 'Unidad luces' },
  { key: 'cuarto_luces', label: 'Cuarto luces' },
  { key: 'antena', label: 'Antena' },
  { key: 'espejos_laterales', label: 'Espejos laterales' },
  { key: 'cristales', label: 'Cristales' },
  { key: 'emblemas', label: 'Emblemas' },
  { key: 'llantas', label: 'Llantas' },
  { key: 'tapones_gasolina', label: 'Tapones gasolina' },
  { key: 'carroceria_sin_golpes', label: 'Carrocería sin golpes' },
  { key: 'claxon', label: 'Claxon' },
  { key: 'instrumentos_tablero', label: 'Instrumentos tablero' },
  { key: 'aire_acondicionado', label: 'Aire acondicionado' },
  { key: 'limpiadores', label: 'Limpiadores' },
  { key: 'radio_estereo', label: 'Radio/Estéreo' },
  { key: 'encendedor', label: 'Encendedor' },
  { key: 'espejo_retrovisor', label: 'Espejo retrovisor' },
  { key: 'ceniceros', label: 'Ceniceros' },
  { key: 'botones_interiores', label: 'Botones interiores' },
  { key: 'manijas_interiores', label: 'Manijas interiores' },
  { key: 'tapetes', label: 'Tapetes' },
  { key: 'vestiduras', label: 'Vestiduras' },
  { key: 'gato', label: 'Gato' },
  { key: 'maneral_gato', label: 'Maneral de gato' },
  { key: 'llave_ruedas', label: 'Llave de ruedas' },
  { key: 'herramientas', label: 'Herramientas' },
  { key: 'traing_seguridad', label: 'Triángulo de seguridad' },
  { key: 'llanta_refaccion', label: 'Llanta de refacción' },
  { key: 'extinguidor', label: 'Extinguidor' },
  { key: 'tapon_aceite', label: 'Tapón de aceite' },
  { key: 'tapon_radiador', label: 'Tapón de radiador' },
  { key: 'filtro_aceite', label: 'Filtro de aceite' },
  { key: 'bateria', label: 'Batería' },
  { key: 'filtro_aire', label: 'Filtro de aire' },
];

