import { Cars } from "../models/cars.model";


export const CarsHeader = [
  'Marca',
  'Linea',
  'Modelo',
  'Color',
  'Serie',
  'Numero Motor',
  'Kilometraje',
  'Cilindros',
  'Fecha Llegada',
  'Precio Venta',
  'Enganche',
  'Estatus',
  'Tipo Adquisicion',
  'Checks',
  'Comentarios',
  'Comentarios Carroceria',
  'Comentarios Llantas',
  'Comentarios Pintura',
  'Comentarios Otros'
]

export const CARS: Cars[] = [
  {
    id: '1',
    tipoAutoId: 'SEDAN',
    sucursalId: 'CDMX-NORTE',
    marca: 'Nissan',
    linea: 'Sentra',
    modelo: '2020',
    color: 'Gris',
    serie: '3N1AB7AP0LY123456',
    numeroMotor: 'MR20123456',
    kilometraje: 35000,
    cilindros: 4,
    fechaLlegada: '2025-08-01',
    precioVenta: 250000,
    enganche: 50000,
    estatus: 'EN VENTA',
    tipoAdquisicion: 'COMPRAS',
    checks: {
      unidadLuces: true,
      cuartosLuces: true,
      antena: false,
      espejosLaterales: true,
      cristales: true,
      emblemas: true,
      llantas: true,
      taponesRines: true,
      moldurasCompletas: true,
      taponGasolina: true,
      carroceriaSinGoles: true,
      claxon: true,
      instrumentosTablero: true,
      aireAcondicionado: true,
      limpiadores: true,
      radioEstereo: true,
      encendedor: false,
      espejoRetrovisor: true,
      ceniceros: false,
      botonesInteriores: true,
      manijasInteriores: true,
      tapetes: true,
      vestiduras: true,
      gato: true,
      maneralGato: true,
      llaveRuedas: true,
      estHerramientas: false,
      trianguloSeguridad: true,
      llantaRefaccion: true,
      extinguidor: true,
      taponAceite: true,
      taponRadiador: true,
      filtroAceite: true,
      bateria: true,
      filtroAire: true
    },
    comentarios: 'Unidad en excelentes condiciones',
    comentariosCarroceria: 'Sin detalles',
    comentariosLlantas: 'Seminuevas',
    comentariosPintura: 'Original',
    comentariosOtros: ''
  },
  {
    id: '2',
    tipoAutoId: 'SUV',
    sucursalId: 'GDL-CENTRO',
    marca: 'Toyota',
    linea: 'RAV4',
    modelo: '2019',
    color: 'Blanco',
    serie: 'JTMBFREV2KJ123456',
    numeroMotor: '2AR123456',
    kilometraje: 48000,
    cilindros: 4,
    fechaLlegada: '2025-07-15',
    precioVenta: 380000,
    enganche: 80000,
    estatus: 'APARTADO',
    tipoAdquisicion: 'CONSIGNA',
    checks: {
      unidadLuces: true,
      cuartosLuces: true,
      antena: true,
      espejosLaterales: true,
      cristales: true,
      emblemas: true,
      llantas: true,
      taponesRines: false,
      moldurasCompletas: true,
      taponGasolina: true,
      carroceriaSinGoles: false,
      claxon: true,
      instrumentosTablero: true,
      aireAcondicionado: true,
      limpiadores: true,
      radioEstereo: true,
      encendedor: true,
      espejoRetrovisor: true,
      ceniceros: false,
      botonesInteriores: true,
      manijasInteriores: true,
      tapetes: true,
      vestiduras: true,
      gato: true,
      maneralGato: false,
      llaveRuedas: true,
      estHerramientas: true,
      trianguloSeguridad: true,
      llantaRefaccion: true,
      extinguidor: true,
      taponAceite: true,
      taponRadiador: true,
      filtroAceite: true,
      bateria: true,
      filtroAire: true
    },
    comentarios: 'Detalle menor en carrocería',
    comentariosCarroceria: 'Golpe leve puerta trasera',
    comentariosLlantas: 'Buenas',
    comentariosPintura: 'Reparación pendiente',
    comentariosOtros: ''
  },
  {
    id: '3',
    tipoAutoId: 'PICKUP',
    sucursalId: 'MTY-SUR',
    marca: 'Ford',
    linea: 'Ranger',
    modelo: '2021',
    color: 'Rojo',
    serie: '1FTER4FH5MLA12345',
    numeroMotor: 'ECOBOOST12345',
    kilometraje: 22000,
    cilindros: 4,
    fechaLlegada: '2025-08-10',
    precioVenta: 520000,
    enganche: 100000,
    estatus: 'EN PAGOS',
    tipoAdquisicion: 'COMPRAS',
    checks: {
      unidadLuces: true,
      cuartosLuces: true,
      antena: true,
      espejosLaterales: true,
      cristales: true,
      emblemas: true,
      llantas: true,
      taponesRines: true,
      moldurasCompletas: true,
      taponGasolina: true,
      carroceriaSinGoles: true,
      claxon: true,
      instrumentosTablero: true,
      aireAcondicionado: true,
      limpiadores: true,
      radioEstereo: true,
      encendedor: true,
      espejoRetrovisor: true,
      ceniceros: false,
      botonesInteriores: true,
      manijasInteriores: true,
      tapetes: true,
      vestiduras: true,
      gato: true,
      maneralGato: true,
      llaveRuedas: true,
      estHerramientas: true,
      trianguloSeguridad: true,
      llantaRefaccion: true,
      extinguidor: true,
      taponAceite: true,
      taponRadiador: true,
      filtroAceite: true,
      bateria: true,
      filtroAire: true
    },
    comentarios: 'Prácticamente nuevo',
    comentariosCarroceria: 'Impecable',
    comentariosLlantas: 'Nuevas',
    comentariosPintura: 'Original',
    comentariosOtros: ''
  },
  {
    id: '4',
    tipoAutoId: 'SEDAN',
    sucursalId: 'PUEBLA-ESTE',
    marca: 'Chevrolet',
    linea: 'Aveo',
    modelo: '2018',
    color: 'Negro',
    serie: 'KL1TD566JJB123456',
    numeroMotor: 'GMX123456',
    kilometraje: 72000,
    cilindros: 4,
    fechaLlegada: '2025-06-25',
    precioVenta: 180000,
    enganche: 30000,
    estatus: 'LIQUIDADO',
    tipoAdquisicion: 'CONSIGNA',
    checks: {
      unidadLuces: true,
      cuartosLuces: false,
      antena: true,
      espejosLaterales: true,
      cristales: true,
      emblemas: false,
      llantas: true,
      taponesRines: false,
      moldurasCompletas: false,
      taponGasolina: true,
      carroceriaSinGoles: false,
      claxon: true,
      instrumentosTablero: true,
      aireAcondicionado: false,
      limpiadores: true,
      radioEstereo: true,
      encendedor: false,
      espejoRetrovisor: true,
      ceniceros: false,
      botonesInteriores: true,
      manijasInteriores: true,
      tapetes: true,
      vestiduras: true,
      gato: true,
      maneralGato: false,
      llaveRuedas: false,
      estHerramientas: false,
      trianguloSeguridad: false,
      llantaRefaccion: true,
      extinguidor: false,
      taponAceite: true,
      taponRadiador: true,
      filtroAceite: true,
      bateria: true,
      filtroAire: true
    },
    comentarios: 'Vehículo con detalles de uso',
    comentariosCarroceria: 'Rayones menores',
    comentariosLlantas: 'Desgastadas',
    comentariosPintura: 'Requiere pulido',
    comentariosOtros: 'Revisión general pendiente'
  },
  {
    id: '5',
    tipoAutoId: 'SUV',
    sucursalId: 'QRO-CENTRO',
    marca: 'Mazda',
    linea: 'CX-5',
    modelo: '2022',
    color: 'Azul Marino',
    serie: 'JM3KFBDY6N0123456',
    numeroMotor: 'SKYACTIV1234',
    kilometraje: 15000,
    cilindros: 4,
    fechaLlegada: '2025-08-18',
    precioVenta: 620000,
    enganche: 120000,
    estatus: 'EN VENTA',
    tipoAdquisicion: 'COMPRAS',
    checks: {
      unidadLuces: true,
      cuartosLuces: true,
      antena: true,
      espejosLaterales: true,
      cristales: true,
      emblemas: true,
      llantas: true,
      taponesRines: true,
      moldurasCompletas: true,
      taponGasolina: true,
      carroceriaSinGoles: true,
      claxon: true,
      instrumentosTablero: true,
      aireAcondicionado: true,
      limpiadores: true,
      radioEstereo: true,
      encendedor: true,
      espejoRetrovisor: true,
      ceniceros: false,
      botonesInteriores: true,
      manijasInteriores: true,
      tapetes: true,
      vestiduras: true,
      gato: true,
      maneralGato: true,
      llaveRuedas: true,
      estHerramientas: true,
      trianguloSeguridad: true,
      llantaRefaccion: true,
      extinguidor: true,
      taponAceite: true,
      taponRadiador: true,
      filtroAceite: true,
      bateria: true,
      filtroAire: true
    },
    comentarios: 'SUV de lujo, único dueño',
    comentariosCarroceria: 'Impecable',
    comentariosLlantas: 'Nuevas',
    comentariosPintura: 'Brillante',
    comentariosOtros: ''
  }
];

